# Generated by Django 4.1.3 on 2024-05-28 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swift', '0005_prompt_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=150)),
                ('tool_context', models.TextField()),
                ('youtube_link', models.URLField()),
                ('inputs', models.JSONField(default=dict)),
                ('keywords', models.JSONField(default=dict)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('tool_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_type', to='swift.tooltype')),
            ],
        ),
    ]
