# Generated by Django 4.1.3 on 2024-05-28 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swift', '0006_tooltype_tooltemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tool_type', models.CharField(choices=[('text_box', 'text box'), ('text_area', 'text area'), ('radio_button', 'radio button'), ('checkbox', 'checkbox')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='tooltemplate',
            name='inputs',
        ),
        migrations.RemoveField(
            model_name='tooltemplate',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='tooltype',
            name='name',
        ),
        migrations.AddField(
            model_name='tooltype',
            name='custom_tool_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tooltype',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tooltype',
            name='tool_type_category',
            field=models.CharField(choices=[('Subject', 'Subject'), ('General', 'General')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tooltemplate',
            name='tool_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_tool_type', to='swift.tooltype'),
        ),
        migrations.CreateModel(
            name='ToolTemplateInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.JSONField(default=dict)),
                ('validation_message', models.CharField(max_length=150)),
                ('sort_order', models.CharField(max_length=150)),
                ('tool_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_input', to='swift.toolinput')),
                ('tool_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_template', to='swift.tooltemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ToolKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=150)),
                ('tool_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_template_keyword', to='swift.tooltemplate')),
            ],
        ),
    ]
